// lib/pharmacy/category-brand-data.ts

import type { PharmacyCategory, PharmacyBrand } from "@/types/pharmacy/category-brand-types";

export const PHARMACY_CATEGORIES: PharmacyCategory[] = [
  {
    categoryId: "1",
    categoryName: "Antibiotics",
    description: "Medications used to treat bacterial infections",
    parentCategory: "Medicines",
    medicineCount: 84,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "1",
    createdBy: "Admin",
    createdDate: "2024-01-12",
    updatedDate: "2024-01-15",
  },
  {
    categoryId: "2",
    categoryName: "Pain Killers",
    description: "Analgesic medications for pain relief",
    parentCategory: "Medicines",
    medicineCount: 56,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "2",
    createdBy: "Admin",
    createdDate: "2024-01-12",
    updatedDate: "2024-01-14",
  },
  {
    categoryId: "3",
    categoryName: "Diabetes",
    description: "Medications for diabetes management",
    parentCategory: "Chronic Care",
    medicineCount: 42,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "3",
    createdBy: "Admin",
    createdDate: "2024-01-15",
    updatedDate: "2024-01-20",
  },
  {
    categoryId: "4",
    categoryName: "Blood Pressure",
    description: "Cardiovascular medications for BP control",
    parentCategory: "Chronic Care",
    medicineCount: 38,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "4",
    createdBy: "Admin",
    createdDate: "2024-01-15",
    updatedDate: "2024-01-18",
  },
  {
    categoryId: "5",
    categoryName: "Heart Medicines",
    description: "Cardiac care medications",
    parentCategory: "Chronic Care",
    medicineCount: 29,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "5",
    createdBy: "Admin",
    createdDate: "2024-01-18",
    updatedDate: "2024-01-22",
  },
  {
    categoryId: "6",
    categoryName: "Respiratory",
    description: "Medications for respiratory conditions",
    parentCategory: "Medicines",
    medicineCount: 33,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "6",
    createdBy: "Admin",
    createdDate: "2024-01-18",
    updatedDate: "2024-01-25",
  },
  {
    categoryId: "7",
    categoryName: "Gastro",
    description: "Gastrointestinal medications",
    parentCategory: "Medicines",
    medicineCount: 27,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "7",
    createdBy: "Admin",
    createdDate: "2024-01-20",
    updatedDate: "2024-01-28",
  },
  {
    categoryId: "8",
    categoryName: "Skin Care",
    description: "Dermatological products and medications",
    parentCategory: "Personal Care",
    medicineCount: 45,
    medicineType: "Consumable",
    gstPercent: "18",
    status: "Active",
    displayOrder: "8",
    createdBy: "Admin",
    createdDate: "2024-01-20",
    updatedDate: "2024-01-30",
  },
  {
    categoryId: "9",
    categoryName: "Injection",
    description: "Injectable medications and solutions",
    parentCategory: "Medicines",
    medicineCount: 18,
    medicineType: "Injection",
    gstPercent: "12",
    status: "Active",
    displayOrder: "9",
    createdBy: "Admin",
    createdDate: "2024-01-22",
    updatedDate: "2024-02-01",
  },
  {
    categoryId: "10",
    categoryName: "IV Fluids",
    description: "Intravenous fluid solutions",
    parentCategory: "Medical Supplies",
    medicineCount: 12,
    medicineType: "Consumable",
    gstPercent: "12",
    status: "Active",
    displayOrder: "10",
    createdBy: "Admin",
    createdDate: "2024-01-22",
    updatedDate: "2024-02-03",
  },
  {
    categoryId: "11",
    categoryName: "Syrups",
    description: "Liquid oral medications",
    parentCategory: "Medicines",
    medicineCount: 31,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "11",
    createdBy: "Admin",
    createdDate: "2024-01-25",
    updatedDate: "2024-02-05",
  },
  {
    categoryId: "12",
    categoryName: "Tablets",
    description: "Solid oral dosage forms",
    parentCategory: "Medicines",
    medicineCount: 96,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "12",
    createdBy: "Admin",
    createdDate: "2024-01-25",
    updatedDate: "2024-02-08",
  },
  {
    categoryId: "13",
    categoryName: "Capsules",
    description: "Encapsulated medications",
    parentCategory: "Medicines",
    medicineCount: 58,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "13",
    createdBy: "Admin",
    createdDate: "2024-01-28",
    updatedDate: "2024-02-10",
  },
  {
    categoryId: "14",
    categoryName: "Drops",
    description: "Ophthalmic and otic drops",
    parentCategory: "Medicines",
    medicineCount: 14,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "14",
    createdBy: "Admin",
    createdDate: "2024-01-28",
    updatedDate: "2024-02-12",
  },
  {
    categoryId: "15",
    categoryName: "Vaccines",
    description: "Immunization products",
    parentCategory: "Preventive Care",
    medicineCount: 9,
    medicineType: "Injection",
    gstPercent: "5",
    status: "Active",
    displayOrder: "15",
    createdBy: "Admin",
    createdDate: "2024-01-30",
    updatedDate: "2024-02-15",
  },
  {
    categoryId: "16",
    categoryName: "Supplements",
    description: "Nutritional and dietary supplements",
    parentCategory: "Personal Care",
    medicineCount: 52,
    medicineType: "Tablet",
    gstPercent: "18",
    status: "Active",
    displayOrder: "16",
    createdBy: "Admin",
    createdDate: "2024-01-30",
    updatedDate: "2024-02-18",
  },
  {
    categoryId: "17",
    categoryName: "OTC Medicines",
    description: "Over-the-counter medications",
    parentCategory: "Medicines",
    medicineCount: 67,
    medicineType: "Tablet",
    gstPercent: "12",
    status: "Active",
    displayOrder: "17",
    createdBy: "Admin",
    createdDate: "2024-02-01",
    updatedDate: "2024-02-20",
  },
];

export const CATEGORY_OPTIONS = [
  "Tablet",
  "Injection",
  "Consumable",
];

export const STATUS_OPTIONS = [
  "Active",
  "Inactive",
];

export const PARENT_CATEGORY_OPTIONS = [
  "Medicines",
  "Chronic Care",
  "Personal Care",
  "Medical Supplies",
  "Preventive Care",
  "None",
];

export const DEFAULT_CATEGORY_FORM: Omit<PharmacyCategory, "medicineCount" | "createdBy" | "createdDate" | "updatedDate"> = {
  categoryName: "",
  description: "",
  parentCategory: "",
  medicineType: "",
  gstPercent: "",
  status: "Active",
  displayOrder: "",
};




export const PHARMACY_BRANDS: PharmacyBrand[] = [
  {
    brandId: "1",
    brandName: "Pfizer",
    medicineCount: 156,
    manufacturer: "Pfizer Inc.",
    country: "United States",
    website: "https://www.pfizer.com",
    licenseNumber: "LIC-2024-001",
    gst: "12",
    supportContact: "+1-800-555-0100",
    status: "Active",
    createdDate: "2024-01-10",
  },
  {
    brandId: "2",
    brandName: "Cipla",
    medicineCount: 243,
    manufacturer: "Cipla Ltd.",
    country: "India",
    website: "https://www.cipla.com",
    licenseNumber: "LIC-2024-002",
    gst: "12",
    supportContact: "+91-22-2345-6789",
    status: "Active",
    createdDate: "2024-01-12",
  },
  {
    brandId: "3",
    brandName: "Sun Pharma",
    medicineCount: 189,
    manufacturer: "Sun Pharmaceutical Industries",
    country: "India",
    website: "https://www.sunpharma.com",
    licenseNumber: "LIC-2024-003",
    gst: "12",
    supportContact: "+91-22-4324-5678",
    status: "Active",
    createdDate: "2024-01-15",
  },
  {
    brandId: "4",
    brandName: "Novartis",
    medicineCount: 134,
    manufacturer: "Novartis AG",
    country: "Switzerland",
    website: "https://www.novartis.com",
    licenseNumber: "LIC-2024-004",
    gst: "12",
    supportContact: "+41-61-324-1111",
    status: "Active",
    createdDate: "2024-01-18",
  },
  {
    brandId: "5",
    brandName: "Dr. Reddy's",
    medicineCount: 167,
    manufacturer: "Dr. Reddy's Laboratories",
    country: "India",
    website: "https://www.drreddys.com",
    licenseNumber: "LIC-2024-005",
    gst: "12",
    supportContact: "+91-40-4900-2900",
    status: "Active",
    createdDate: "2024-01-20",
  },
  {
    brandId: "6",
    brandName: "Lupin",
    medicineCount: 142,
    manufacturer: "Lupin Limited",
    country: "India",
    website: "https://www.lupin.com",
    licenseNumber: "LIC-2024-006",
    gst: "12",
    supportContact: "+91-22-2652-2323",
    status: "Active",
    createdDate: "2024-01-22",
  },
  {
    brandId: "7",
    brandName: "AstraZeneca",
    medicineCount: 121,
    manufacturer: "AstraZeneca PLC",
    country: "United Kingdom",
    website: "https://www.astrazeneca.com",
    licenseNumber: "LIC-2024-007",
    gst: "12",
    supportContact: "+44-20-7946-1000",
    status: "Active",
    createdDate: "2024-01-25",
  },
  {
    brandId: "8",
    brandName: "GSK",
    medicineCount: 178,
    manufacturer: "GlaxoSmithKline",
    country: "United Kingdom",
    website: "https://www.gsk.com",
    licenseNumber: "LIC-2024-008",
    gst: "12",
    supportContact: "+44-20-8785-1000",
    status: "Active",
    createdDate: "2024-01-28",
  },
  {
    brandId: "9",
    brandName: "Cadila",
    medicineCount: 98,
    manufacturer: "Cadila Pharmaceuticals",
    country: "India",
    website: "https://www.cadila.com",
    licenseNumber: "LIC-2024-009",
    gst: "12",
    supportContact: "+91-2717-220000",
    status: "Active",
    createdDate: "2024-02-01",
  },
  {
    brandId: "10",
    brandName: "Alkem",
    medicineCount: 87,
    manufacturer: "Alkem Laboratories",
    country: "India",
    website: "https://www.alkem.com",
    licenseNumber: "LIC-2024-010",
    gst: "12",
    supportContact: "+91-22-6646-6000",
    status: "Active",
    createdDate: "2024-02-05",
  },
  {
    brandId: "11",
    brandName: "Mankind",
    medicineCount: 112,
    manufacturer: "Mankind Pharma",
    country: "India",
    website: "https://www.mankindpharma.com",
    licenseNumber: "LIC-2024-011",
    gst: "12",
    supportContact: "+91-11-4333-3000",
    status: "Active",
    createdDate: "2024-02-08",
  },
  {
    brandId: "12",
    brandName: "Intas",
    medicineCount: 76,
    manufacturer: "Intas Pharmaceuticals",
    country: "India",
    website: "https://www.intas.com",
    licenseNumber: "LIC-2024-012",
    gst: "12",
    supportContact: "+91-2717-666666",
    status: "Inactive",
    createdDate: "2024-02-10",
  },
];


export const COUNTRY_OPTIONS = [
  "India",
  "United States",
  "United Kingdom",
  "Switzerland",
  "Germany",
  "France",
  "Japan",
  "Other",
];


export const DEFAULT_BRAND_FORM: Omit<PharmacyBrand, "brandId" | "medicineCount" | "createdDate"> = {
  brandName: "",
  manufacturer: "",
  country: "",
  website: "",
  licenseNumber: "",
  gst: "",
  supportContact: "",
  status: "Active",
};