
import type { ExpiryMedicineItem } from "@/types/pharmacy/expiry-medicines-types";

export const EXPIRY_MEDICINES: ExpiryMedicineItem[] = [
  {
    id: "1",
    medicineName: "Atorvastatin 20",
    genericName: "Atorvastatin",
    brand: "Dr. Reddy's",
    category: "Heart Medicines",
    batchNo: "H201",
    rack: "C-08",
    stock: 0,
    expiryDate: "12 Jul 2026",
    supplier: "Cipla Wholesale",
    status: "Expired",
    daysLeft: -22,
  },
  {
    id: "2",
    medicineName: "Azithromycin 500",
    genericName: "Azithromycin",
    brand: "Sun Pharma",
    category: "Antibiotics",
    batchNo: "A102",
    rack: "B-12",
    stock: 24,
    expiryDate: "18 Aug 2026",
    supplier: "Apollo Pharma Traders",
    status: "Near Expiry",
    daysLeft: 15,
  },
  {
    id: "3",
    medicineName: "Pantoprazole 40",
    genericName: "Pantoprazole",
    brand: "Lupin",
    category: "Gastro",
    batchNo: "G441",
    rack: "D-03",
    stock: 42,
    expiryDate: "02 Sep 2026",
    supplier: "MedPlus Distributors",
    status: "Near Expiry",
    daysLeft: 30,
  },
  {
    id: "4",
    medicineName: "Vitamin D3 60K",
    genericName: "Cholecalciferol",
    brand: "Zydus",
    category: "Supplements",
    batchNo: "V118",
    rack: "S-02",
    stock: 18,
    expiryDate: "25 Sep 2026",
    supplier: "Sun Pharma Supply Co.",
    status: "Near Expiry",
    daysLeft: 53,
  },
  {
    id: "5",
    medicineName: "Clindamycin Gel",
    genericName: "Clindamycin",
    brand: "Sun Pharma",
    category: "Skin Care",
    batchNo: "C901",
    rack: "SK-07",
    stock: 8,
    expiryDate: "15 Jun 2026",
    supplier: "Sun Pharma Supply Co.",
    status: "Expired",
    daysLeft: -49,
  },
  {
    id: "6",
    medicineName: "Domperidone 10",
    genericName: "Domperidone",
    brand: "Alkem",
    category: "Gastro",
    batchNo: "D771",
    rack: "D-08",
    stock: 34,
    expiryDate: "08 Oct 2026",
    supplier: "Apollo Pharma Traders",
    status: "Near Expiry",
    daysLeft: 66,
  },
  {
    id: "7",
    medicineName: "Cefixime 200",
    genericName: "Cefixime",
    brand: "Abbott",
    category: "Antibiotics",
    batchNo: "CF220",
    rack: "B-18",
    stock: 16,
    expiryDate: "28 May 2026",
    supplier: "MedPlus Distributors",
    status: "Expired",
    daysLeft: -67,
  },
  {
    id: "8",
    medicineName: "Metformin 500",
    genericName: "Metformin",
    brand: "Mankind",
    category: "Diabetes",
    batchNo: "M620",
    rack: "A-09",
    stock: 58,
    expiryDate: "20 Oct 2026",
    supplier: "Cipla Wholesale",
    status: "Near Expiry",
    daysLeft: 78,
  },
];