// lib/pharmacy/inventory-data.ts

import type { InventoryItem } from "@/types/pharmacy/inventory-types";

// In your real project, derive this from Medicine + Batch master data:
// currentStock = sum of batch.stock for the medicine
// available = currentStock - reserved - blocked - damaged - expired
export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "1",
    medicineId: "1",
    medicineName: "Paracetamol 650",
    medicineCode: "MED-2024-001",
    category: "Pain Killers",
    warehouse: "Main Warehouse",
    unit: "Strip",
    currentStock: 450,
    available: 380,
    reserved: 40,
    blocked: 10,
    damaged: 5,
    expired: 15,
    issuedToday: 65,
    purchasedToday: 200,
    transferred: 30,
    reorderLevel: 150,
    stockValue: "20250",
    lastUpdated: "2024-08-09 14:30",
    status: "In Stock",
  },
  {
    id: "2",
    medicineId: "2",
    medicineName: "Azithromycin 500",
    medicineCode: "MED-2024-002",
    category: "Antibiotics",
    warehouse: "Central Store",
    unit: "Strip",
    currentStock: 40,
    available: 30,
    reserved: 5,
    blocked: 0,
    damaged: 0,
    expired: 5,
    issuedToday: 12,
    purchasedToday: 0,
    transferred: 0,
    reorderLevel: 60,
    stockValue: "2600",
    lastUpdated: "2024-08-09 11:15",
    status: "Low Stock",
  },
  {
    id: "3",
    medicineId: "3",
    medicineName: "Atorvastatin 20",
    medicineCode: "MED-2024-003",
    category: "Heart Medicines",
    warehouse: "Main Warehouse",
    unit: "Strip",
    currentStock: 0,
    available: 0,
    reserved: 0,
    blocked: 0,
    damaged: 0,
    expired: 0,
    issuedToday: 0,
    purchasedToday: 0,
    transferred: 0,
    reorderLevel: 50,
    stockValue: "0",
    lastUpdated: "2024-08-08 09:00",
    status: "Out of Stock",
  },
  {
    id: "4",
    medicineId: "4",
    medicineName: "Metformin 500",
    medicineCode: "MED-2024-004",
    category: "Diabetes",
    warehouse: "Branch Store - North",
    unit: "Strip",
    currentStock: 2650,
    available: 2400,
    reserved: 100,
    blocked: 50,
    damaged: 20,
    expired: 80,
    issuedToday: 150,
    purchasedToday: 0,
    transferred: 200,
    reorderLevel: 150,
    stockValue: "50350",
    lastUpdated: "2024-08-09 16:45",
    status: "Overstock",
  },
  {
    id: "5",
    medicineId: "5",
    medicineName: "Amoxicillin 250",
    medicineCode: "MED-2024-005",
    category: "Antibiotics",
    warehouse: "Central Store",
    unit: "Strip",
    currentStock: 320,
    available: 280,
    reserved: 20,
    blocked: 5,
    damaged: 0,
    expired: 15,
    issuedToday: 45,
    purchasedToday: 100,
    transferred: 0,
    reorderLevel: 100,
    stockValue: "11200",
    lastUpdated: "2024-08-09 13:20",
    status: "In Stock",
  },
  {
    id: "6",
    medicineId: "6",
    medicineName: "Cetirizine 10",
    medicineCode: "MED-2024-006",
    category: "Respiratory",
    warehouse: "Main Warehouse",
    unit: "Strip",
    currentStock: 85,
    available: 70,
    reserved: 10,
    blocked: 0,
    damaged: 0,
    expired: 5,
    issuedToday: 25,
    purchasedToday: 0,
    transferred: 0,
    reorderLevel: 100,
    stockValue: "1700",
    lastUpdated: "2024-08-09 10:05",
    status: "Low Stock",
  },
];

export const WAREHOUSE_OPTIONS = ["Main Warehouse", "Central Store", "Branch Store - North", "Branch Store - South", "Cold Storage"];
export const CATEGORY_OPTIONS = ["Pain Killers", "Antibiotics", "Heart Medicines", "Diabetes", "Respiratory"];
export const STATUS_OPTIONS = ["In Stock", "Low Stock", "Out of Stock", "Overstock"];
export const ADJUSTMENT_TYPE_OPTIONS = ["Damaged", "Expired", "Blocked", "Transferred", "Reserved"];