// lib/admin/pharmacy/medicine-sales-insights-data.ts
import type { MedicineSalesRecord } from "@/types/pharmacy/medicine-sales-insights-types";

export const LAST_6_MONTH_OPTIONS = [
  "Mar 2026",
  "Apr 2026",
  "May 2026",
  "Jun 2026",
  "Jul 2026",
  "Aug 2026",
];

export const MEDICINE_SALES_RECORDS: MedicineSalesRecord[] = [
  {
    id: "1",
    medicineName: "Paracetamol 650",
    genericName: "Paracetamol",
    brand: "Cipla",
    category: "Pain Killers",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 610 },
      { month: "Apr 2026", unitsSold: 655 },
      { month: "May 2026", unitsSold: 690 },
      { month: "Jun 2026", unitsSold: 720 },
      { month: "Jul 2026", unitsSold: 760 },
      { month: "Aug 2026", unitsSold: 790 },
    ],
  },
  {
    id: "2",
    medicineName: "Azithromycin 500",
    genericName: "Azithromycin",
    brand: "Sun Pharma",
    category: "Antibiotics",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 420 },
      { month: "Apr 2026", unitsSold: 460 },
      { month: "May 2026", unitsSold: 505 },
      { month: "Jun 2026", unitsSold: 550 },
      { month: "Jul 2026", unitsSold: 520 },
      { month: "Aug 2026", unitsSold: 545 },
    ],
  },
  {
    id: "3",
    medicineName: "Atorvastatin 20",
    genericName: "Atorvastatin",
    brand: "Dr. Reddy's",
    category: "Heart Medicines",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 300 },
      { month: "Apr 2026", unitsSold: 320 },
      { month: "May 2026", unitsSold: 340 },
      { month: "Jun 2026", unitsSold: 365 },
      { month: "Jul 2026", unitsSold: 390 },
      { month: "Aug 2026", unitsSold: 410 },
    ],
  },
  {
    id: "4",
    medicineName: "Metformin 500",
    genericName: "Metformin",
    brand: "Mankind",
    category: "Diabetes",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 530 },
      { month: "Apr 2026", unitsSold: 560 },
      { month: "May 2026", unitsSold: 590 },
      { month: "Jun 2026", unitsSold: 610 },
      { month: "Jul 2026", unitsSold: 640 },
      { month: "Aug 2026", unitsSold: 670 },
    ],
  },
  {
    id: "5",
    medicineName: "Pantoprazole 40",
    genericName: "Pantoprazole",
    brand: "Lupin",
    category: "Gastro",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 350 },
      { month: "Apr 2026", unitsSold: 370 },
      { month: "May 2026", unitsSold: 395 },
      { month: "Jun 2026", unitsSold: 415 },
      { month: "Jul 2026", unitsSold: 435 },
      { month: "Aug 2026", unitsSold: 460 },
    ],
  },
  {
    id: "6",
    medicineName: "Cefixime 200",
    genericName: "Cefixime",
    brand: "Abbott",
    category: "Antibiotics",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 210 },
      { month: "Apr 2026", unitsSold: 225 },
      { month: "May 2026", unitsSold: 245 },
      { month: "Jun 2026", unitsSold: 260 },
      { month: "Jul 2026", unitsSold: 255 },
      { month: "Aug 2026", unitsSold: 275 },
    ],
  },
  {
    id: "7",
    medicineName: "Losartan 50",
    genericName: "Losartan",
    brand: "Torrent",
    category: "Blood Pressure",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 280 },
      { month: "Apr 2026", unitsSold: 295 },
      { month: "May 2026", unitsSold: 310 },
      { month: "Jun 2026", unitsSold: 328 },
      { month: "Jul 2026", unitsSold: 340 },
      { month: "Aug 2026", unitsSold: 355 },
    ],
  },
  {
    id: "8",
    medicineName: "Vitamin D3 60K",
    genericName: "Cholecalciferol",
    brand: "Zydus",
    category: "Supplements",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 150 },
      { month: "Apr 2026", unitsSold: 158 },
      { month: "May 2026", unitsSold: 162 },
      { month: "Jun 2026", unitsSold: 176 },
      { month: "Jul 2026", unitsSold: 180 },
      { month: "Aug 2026", unitsSold: 194 },
    ],
  },
  {
    id: "9",
    medicineName: "Domperidone 10",
    genericName: "Domperidone",
    brand: "Alkem",
    category: "Gastro",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 58 },
      { month: "Apr 2026", unitsSold: 62 },
      { month: "May 2026", unitsSold: 60 },
      { month: "Jun 2026", unitsSold: 66 },
      { month: "Jul 2026", unitsSold: 64 },
      { month: "Aug 2026", unitsSold: 69 },
    ],
  },
  {
    id: "10",
    medicineName: "Clindamycin Gel",
    genericName: "Clindamycin",
    brand: "Sun Pharma",
    category: "Skin Care",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 42 },
      { month: "Apr 2026", unitsSold: 45 },
      { month: "May 2026", unitsSold: 43 },
      { month: "Jun 2026", unitsSold: 47 },
      { month: "Jul 2026", unitsSold: 50 },
      { month: "Aug 2026", unitsSold: 52 },
    ],
  },
  {
    id: "11",
    medicineName: "Terbinafine Cream",
    genericName: "Terbinafine",
    brand: "Cipla",
    category: "Skin Care",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 35 },
      { month: "Apr 2026", unitsSold: 37 },
      { month: "May 2026", unitsSold: 36 },
      { month: "Jun 2026", unitsSold: 39 },
      { month: "Jul 2026", unitsSold: 41 },
      { month: "Aug 2026", unitsSold: 40 },
    ],
  },
  {
    id: "12",
    medicineName: "Colchicine 0.5",
    genericName: "Colchicine",
    brand: "Mankind",
    category: "Pain Killers",
    monthlySales: [
      { month: "Mar 2026", unitsSold: 20 },
      { month: "Apr 2026", unitsSold: 22 },
      { month: "May 2026", unitsSold: 21 },
      { month: "Jun 2026", unitsSold: 24 },
      { month: "Jul 2026", unitsSold: 23 },
      { month: "Aug 2026", unitsSold: 25 },
    ],
  },
];