// lib/pharmacy/medicine-data.ts

import type { Medicine, MedicineFormData } from "@/types/pharmacy/medicine-types";

export const MEDICINES: Medicine[] = [
  {
    id: "1",
    medicineCode: "MED-2024-001",
    barcode: "8901234567891",
    medicineName: "Paracetamol 650",
    generic: "Paracetamol",
    brand: "Cipla",
    strength: "650 mg",
    dosageForm: "Tablet",
    packSize: "10x10",
    unit: "Strip",
    route: "Oral",
    atcCode: "N02BE01",
    category: "Pain Killers",
    subCategory: "Analgesic",
    manufacturer: "Cipla Ltd.",
    primarySupplier: "Rakesh Kumar",
    hsnCode: "30049099",
    gstPercent: "12",
    purchaseUnit: "Box",
    issueUnit: "Strip",
    storageCondition: "Store Below 25°C",
    storageTemperature: "15-25°C",
    controlledDrug: false,
    narcotic: false,
    lasaMedicine: false,
    highAlertMedicine: false,
    lookAlikeSoundAlike: false,
    prescriptionRequired: false,
    expiryAlertDays: "90",
    reorderLevel: "150",
    maximumStock: "600",
    minimumStock: 100,
    reservedStock: "20",
    blockedStock: "0",
    rack: "A-04",
    shelf: "S2",
    bin: "B12",
    abcClassification: "A",
    vedClassification: "E",
    status: "Active",
    createdBy: "Admin",
    updatedBy: "Admin",
    batches: [
      { id: "B1", batchNo: "P001", purchasePrice: 20, sellingPrice: 25, mrp: 28, stock: 100, expiryDate: "Jan 2027", addedOn: "10 Jan 2024" },
      { id: "B2", batchNo: "P002", purchasePrice: 40, sellingPrice: 45, mrp: 56, stock: 200, expiryDate: "Dec 2028", addedOn: "05 Mar 2024" },
      { id: "B3", batchNo: "P003", purchasePrice: 38, sellingPrice: 44, mrp: 57, stock: 150, expiryDate: "Jun 2029", addedOn: "18 Jun 2024" },
    ],
  },
  {
    id: "2",
    medicineCode: "MED-2024-002",
    barcode: "8901234567892",
    medicineName: "Azithromycin 500",
    generic: "Azithromycin",
    brand: "Sun Pharma",
    strength: "500 mg",
    dosageForm: "Tablet",
    packSize: "1x3",
    unit: "Strip",
    route: "Oral",
    atcCode: "J01FA10",
    category: "Antibiotics",
    subCategory: "Macrolide",
    manufacturer: "Sun Pharmaceutical Industries",
    primarySupplier: "Anita Desai",
    hsnCode: "30042099",
    gstPercent: "12",
    purchaseUnit: "Box",
    issueUnit: "Strip",
    storageCondition: "Store Below 30°C",
    storageTemperature: "15-30°C",
    controlledDrug: false,
    narcotic: false,
    lasaMedicine: true,
    highAlertMedicine: false,
    lookAlikeSoundAlike: true,
    prescriptionRequired: true,
    expiryAlertDays: "60",
    reorderLevel: "60",
    maximumStock: "300",
    minimumStock: 80,
    reservedStock: "10",
    blockedStock: "0",
    rack: "B-12",
    shelf: "S1",
    bin: "B05",
    abcClassification: "B",
    vedClassification: "V",
    status: "Active",
    createdBy: "Admin",
    updatedBy: "Front Desk",
    batches: [
      { id: "B4", batchNo: "A101", purchasePrice: 55, sellingPrice: 65, mrp: 78, stock: 40, expiryDate: "Mar 2027", addedOn: "12 Feb 2024" },
      { id: "B5", batchNo: "A102", purchasePrice: 58, sellingPrice: 68, mrp: 80, stock: 0, expiryDate: "Sep 2026", addedOn: "20 Apr 2024" },
    ],
  },
  {
    id: "3",
    medicineCode: "MED-2024-003",
    barcode: "8901234567893",
    medicineName: "Atorvastatin 20",
    generic: "Atorvastatin",
    brand: "Dr. Reddy's",
    strength: "20 mg",
    dosageForm: "Tablet",
    packSize: "1x10",
    unit: "Strip",
    route: "Oral",
    atcCode: "C10AA05",
    category: "Heart Medicines",
    subCategory: "Statin",
    manufacturer: "Dr. Reddy's Laboratories",
    primarySupplier: "Suresh Menon",
    hsnCode: "30049099",
    gstPercent: "12",
    purchaseUnit: "Box",
    issueUnit: "Strip",
    storageCondition: "Store Below 25°C",
    storageTemperature: "15-25°C",
    controlledDrug: false,
    narcotic: false,
    lasaMedicine: false,
    highAlertMedicine: false,
    lookAlikeSoundAlike: false,
    prescriptionRequired: true,
    expiryAlertDays: "90",
    reorderLevel: "50",
    maximumStock: "250",
    minimumStock: 60,
    reservedStock: "0",
    blockedStock: "0",
    rack: "C-08",
    shelf: "S3",
    bin: "B18",
    abcClassification: "B",
    vedClassification: "E",
    status: "Active",
    createdBy: "Admin",
    updatedBy: "Admin",
    batches: [
      { id: "B6", batchNo: "H201", purchasePrice: 32, sellingPrice: 38, mrp: 45, stock: 0, expiryDate: "Nov 2026", addedOn: "08 Jan 2024" },
    ],
  },
  {
    id: "4",
    medicineCode: "MED-2024-004",
    barcode: "8901234567894",
    medicineName: "Metformin 500",
    generic: "Metformin Hydrochloride",
    brand: "Mankind",
    strength: "500 mg",
    dosageForm: "Tablet",
    packSize: "1x15",
    unit: "Strip",
    route: "Oral",
    atcCode: "A10BA02",
    category: "Diabetes",
    subCategory: "Biguanide",
    manufacturer: "Mankind Pharma",
    primarySupplier: "Rakesh Kumar",
    hsnCode: "30049099",
    gstPercent: "12",
    purchaseUnit: "Box",
    issueUnit: "Strip",
    storageCondition: "Store Below 25°C",
    storageTemperature: "15-25°C",
    controlledDrug: false,
    narcotic: false,
    lasaMedicine: false,
    highAlertMedicine: true,
    lookAlikeSoundAlike: false,
    prescriptionRequired: true,
    expiryAlertDays: "120",
    reorderLevel: "150",
    maximumStock: "500",
    minimumStock: 120,
    reservedStock: "30",
    blockedStock: "10",
    rack: "A-09",
    shelf: "S1",
    bin: "B02",
    abcClassification: "A",
    vedClassification: "V",
    status: "Active",
    createdBy: "Admin",
    updatedBy: "Admin",
    batches: [
      { id: "B7", batchNo: "D301", purchasePrice: 15, sellingPrice: 19, mrp: 24, stock: 300, expiryDate: "Feb 2028", addedOn: "15 Jan 2024" },
    ],
  },
];

export const DEFAULT_MEDICINE_FORM: MedicineFormData = {
  barcode: "",
  medicineName: "",
  generic: "",
  brand: "",
  strength: "",
  dosageForm: "",
  packSize: "",
  unit: "",
  route: "",
  atcCode: "",
  category: "",
  subCategory: "",
  manufacturer: "",
  primarySupplier: "",
  hsnCode: "",
  gstPercent: "",
  purchaseUnit: "",
  issueUnit: "",
  storageCondition: "",
  storageTemperature: "",
  controlledDrug: false,
  narcotic: false,
  lasaMedicine: false,
  highAlertMedicine: false,
  lookAlikeSoundAlike: false,
  prescriptionRequired: false,
  expiryAlertDays: "",
  reorderLevel: "",
  maximumStock: "",
  minimumStock: 0,
  reservedStock: "0",
  blockedStock: "0",
  rack: "",
  shelf: "",
  bin: "",
  abcClassification: "",
  vedClassification: "",
  status: "Active",
};

export const CATEGORY_OPTIONS = [
  "Antibiotics", "Pain Killers", "Diabetes", "Blood Pressure", "Heart Medicines",
  "Respiratory", "Gastro", "Skin Care",
];
export const SUB_CATEGORY_OPTIONS = [
  "Analgesic", "Macrolide", "Statin", "Biguanide", "Antihypertensive",
  "Bronchodilator", "Antacid", "Antifungal", "Other",
];
export const BRAND_OPTIONS = ["Sun Pharma", "Cipla", "Mankind", "Dr. Reddy's", "Abbott", "Alkem", "Lupin", "Zydus", "Torrent"];
export const MANUFACTURER_OPTIONS = [
  "Cipla Ltd.", "Sun Pharmaceutical Industries", "Dr. Reddy's Laboratories",
  "Mankind Pharma", "Abbott Healthcare", "Alkem Laboratories", "Lupin Limited",
  "Zydus Lifesciences", "Torrent Pharmaceuticals",
];
export const SUPPLIER_OPTIONS = ["Rakesh Kumar", "Anita Desai", "Suresh Menon", "Priya Nair"];

export const DOSAGE_FORM_OPTIONS = [
  "Tablet", "Capsule", "Syrup", "Injection", "Drops", "Ointment", "Cream",
  "Inhaler", "Suspension", "Powder", "Gel",
];
export const UNIT_OPTIONS = ["Strip", "Bottle", "Vial", "Ampoule", "Tube", "Sachet", "Piece", "Box"];
export const ROUTE_OPTIONS = ["Oral", "Intravenous", "Intramuscular", "Subcutaneous", "Topical", "Inhalation", "Ophthalmic", "Nasal", "Rectal"];
export const PURCHASE_UNIT_OPTIONS = ["Box", "Carton", "Case", "Strip", "Bottle"];
export const ISSUE_UNIT_OPTIONS = ["Strip", "Bottle", "Vial", "Piece", "Tablet"];
export const STORAGE_CONDITION_OPTIONS = [
  "Store Below 25°C", "Store Below 30°C", "Refrigerate 2-8°C", "Store in Cool Dry Place",
  "Protect From Light", "Freeze -20°C",
];
export const ABC_OPTIONS = ["A", "B", "C"];
export const VED_OPTIONS = ["V", "E", "D"];
export const STATUS_OPTIONS = ["Active", "Inactive"];