import type { PharmacySale } from "@/types/pharmacy/sales-types";

function calcMedicineAmount(qty: number, price: number) {
  return qty * price;
}

export const PHARMACY_SALES: PharmacySale[] = [
  {
    id: "1",
    billNumber: "PHM240520001",
    billDate: "2024-05-20",
    billTime: "11:40 AM",
    patientName: "Ravi Sharma",
    uhid: "UHID12345685",
    age: 48,
    gender: "Male",
    patientType: "IPD",
    ward: "Semi Private",
    bed: "B-203",
    doctorName: "Dr. Amit Verma",
    department: "Cardiology",
    prescriptionNumber: "RX-240520-001",
    billType: "Credit",
    paymentMode: "Credit",
    paymentStatus: "Pending",
    subTotal: 460,
    discountPercent: 5,
    discountAmount: 23,
    gstPercent: 12,
    gstAmount: 52.44,
    totalAmount: 489.44,
    medicines: [
      { id: "M1", medicineName: "Tab. Aspirin", strength: "75 mg", quantity: 30, unitPrice: 2, amount: calcMedicineAmount(30, 2) },
      { id: "M2", medicineName: "Tab. Atorvastatin", strength: "20 mg", quantity: 30, unitPrice: 5, amount: calcMedicineAmount(30, 5) },
      { id: "M3", medicineName: "Tab. Metoprolol", strength: "25 mg", quantity: 30, unitPrice: 3, amount: calcMedicineAmount(30, 3) },
      { id: "M4", medicineName: "Tab. Pantoprazole", strength: "40 mg", quantity: 10, unitPrice: 4, amount: calcMedicineAmount(10, 4) },
    ],
  },
  {
    id: "2",
    billNumber: "PHM240520002",
    billDate: "2024-05-20",
    billTime: "10:15 AM",
    patientName: "Sunita Devi",
    uhid: "UHID12345686",
    age: 60,
    gender: "Female",
    patientType: "IPD",
    ward: "General Ward",
    bed: "G-105",
    doctorName: "Dr. Priya Nair",
    department: "Neurology",
    prescriptionNumber: "RX-240520-002",
    billType: "Cash",
    paymentMode: "Cash",
    paymentStatus: "Paid",
    subTotal: 240,
    discountPercent: 0,
    discountAmount: 0,
    gstPercent: 12,
    gstAmount: 28.8,
    totalAmount: 268.8,
    medicines: [
      { id: "M5", medicineName: "Tab. Gabapentin", strength: "100 mg", quantity: 30, unitPrice: 6, amount: calcMedicineAmount(30, 6) },
      { id: "M6", medicineName: "Cap. Vitamin D3", strength: "60000 IU", quantity: 4, unitPrice: 15, amount: calcMedicineAmount(4, 15) },
    ],
  },
  {
    id: "3",
    billNumber: "PHM240521003",
    billDate: "2024-05-21",
    billTime: "09:05 AM",
    patientName: "Arjun Mehta",
    uhid: "UHID12345690",
    age: 34,
    gender: "Male",
    patientType: "OPD",
    doctorName: "Dr. Kavita Rao",
    department: "General Medicine",
    prescriptionNumber: "RX-240521-003",
    billType: "Cash",
    paymentMode: "UPI",
    paymentStatus: "Paid",
    subTotal: 180,
    discountPercent: 0,
    discountAmount: 0,
    gstPercent: 12,
    gstAmount: 21.6,
    totalAmount: 201.6,
    medicines: [
      { id: "M7", medicineName: "Tab. Paracetamol 650", strength: "650 mg", quantity: 10, unitPrice: 3, amount: calcMedicineAmount(10, 3) },
      { id: "M8", medicineName: "Cap. Amoxicillin", strength: "500 mg", quantity: 15, unitPrice: 10, amount: calcMedicineAmount(15, 10) },
    ],
  },
  {
    id: "4",
    billNumber: "PHM240522004",
    billDate: "2024-05-22",
    billTime: "02:30 PM",
    patientName: "Meena Kapoor",
    uhid: "UHID12345699",
    age: 29,
    gender: "Female",
    patientType: "Emergency",
    doctorName: "Dr. Sameer Joshi",
    department: "Emergency Medicine",
    prescriptionNumber: "RX-240522-004",
    billType: "Cash",
    paymentMode: "Card",
    paymentStatus: "Paid",
    subTotal: 620,
    discountPercent: 0,
    discountAmount: 0,
    gstPercent: 12,
    gstAmount: 74.4,
    totalAmount: 694.4,
    medicines: [
      { id: "M9", medicineName: "Inj. Tramadol", strength: "50 mg/ml", quantity: 2, unitPrice: 60, amount: calcMedicineAmount(2, 60) },
      { id: "M10", medicineName: "IV Normal Saline", strength: "500 ml", quantity: 4, unitPrice: 125, amount: calcMedicineAmount(4, 125) },
    ],
  },
  {
    id: "5",
    billNumber: "PHM240523005",
    billDate: "2024-05-23",
    billTime: "07:50 PM",
    patientName: "Ramesh Iyer",
    uhid: "UHID12345702",
    age: 66,
    gender: "Male",
    patientType: "ICU",
    ward: "ICU",
    bed: "ICU-04",
    doctorName: "Dr. Anjali Deshmukh",
    department: "Critical Care",
    prescriptionNumber: "RX-240523-005",
    billType: "Credit",
    paymentMode: "Insurance",
    paymentStatus: "Partially Paid",
    subTotal: 1450,
    discountPercent: 10,
    discountAmount: 145,
    gstPercent: 12,
    gstAmount: 156.6,
    totalAmount: 1461.6,
    medicines: [
      { id: "M11", medicineName: "Inj. Ceftriaxone", strength: "1 g", quantity: 6, unitPrice: 90, amount: calcMedicineAmount(6, 90) },
      { id: "M12", medicineName: "Inj. Furosemide", strength: "10 mg/ml", quantity: 4, unitPrice: 45, amount: calcMedicineAmount(4, 45) },
      { id: "M13", medicineName: "Human Insulin", strength: "100 IU/ml", quantity: 2, unitPrice: 220, amount: calcMedicineAmount(2, 220) },
    ],
  },
  {
    id: "6",
    billNumber: "PHM240524006",
    billDate: "2024-05-24",
    billTime: "12:10 PM",
    patientName: "Divya Nair",
    uhid: "UHID12345715",
    age: 41,
    gender: "Female",
    patientType: "OPD",
    doctorName: "Dr. Kavita Rao",
    department: "Dermatology",
    prescriptionNumber: "RX-240524-006",
    billType: "Cash",
    paymentMode: "Cash",
    paymentStatus: "Paid",
    subTotal: 95,
    discountPercent: 0,
    discountAmount: 0,
    gstPercent: 18,
    gstAmount: 17.1,
    totalAmount: 112.1,
    medicines: [
      { id: "M14", medicineName: "Cetirizine 10mg", strength: "10 mg", quantity: 10, unitPrice: 2.5, amount: calcMedicineAmount(10, 2.5) },
      { id: "M15", medicineName: "Betamethasone Cream", strength: "0.1%", quantity: 1, unitPrice: 70, amount: calcMedicineAmount(1, 70) },
    ],
  },
  {
    id: "7",
    billNumber: "PHM240525007",
    billDate: "2024-05-25",
    billTime: "05:45 PM",
    patientName: "Karan Malhotra",
    uhid: "UHID12345730",
    age: 52,
    gender: "Male",
    patientType: "IPD",
    ward: "Private",
    bed: "P-08",
    doctorName: "Dr. Amit Verma",
    department: "Cardiology",
    prescriptionNumber: "RX-240525-007",
    billType: "Credit",
    paymentMode: "Credit",
    paymentStatus: "Pending",
    subTotal: 830,
    discountPercent: 5,
    discountAmount: 41.5,
    gstPercent: 12,
    gstAmount: 94.62,
    totalAmount: 883.12,
    medicines: [
      { id: "M16", medicineName: "Tab. Clopidogrel", strength: "75 mg", quantity: 30, unitPrice: 8, amount: calcMedicineAmount(30, 8) },
      { id: "M17", medicineName: "Tab. Rosuvastatin", strength: "10 mg", quantity: 30, unitPrice: 10, amount: calcMedicineAmount(30, 10) },
      { id: "M18", medicineName: "Tab. Metoprolol", strength: "50 mg", quantity: 20, unitPrice: 4, amount: calcMedicineAmount(20, 4) },
    ],
  },
  {
    id: "8",
    billNumber: "PHM240526008",
    billDate: "2024-05-26",
    billTime: "08:20 AM",
    patientName: "Neha Kulkarni",
    uhid: "UHID12345740",
    age: 25,
    gender: "Female",
    patientType: "Emergency",
    doctorName: "Dr. Sameer Joshi",
    department: "Emergency Medicine",
    prescriptionNumber: "RX-240526-008",
    billType: "Cash",
    paymentMode: "UPI",
    paymentStatus: "Paid",
    subTotal: 340,
    discountPercent: 0,
    discountAmount: 0,
    gstPercent: 12,
    gstAmount: 40.8,
    totalAmount: 380.8,
    medicines: [
      { id: "M19", medicineName: "Inj. Diclofenac", strength: "75 mg/3ml", quantity: 2, unitPrice: 35, amount: calcMedicineAmount(2, 35) },
      { id: "M20", medicineName: "ORS Sachet", strength: "21.8 g", quantity: 10, unitPrice: 12, amount: calcMedicineAmount(10, 12) },
      { id: "M21", medicineName: "Tab. Domperidone", strength: "10 mg", quantity: 10, unitPrice: 4, amount: calcMedicineAmount(10, 4) },
    ],
  },
];

export const PATIENT_TYPE_OPTIONS = ["IPD", "OPD", "ICU", "Emergency"];
export const BILL_TYPE_OPTIONS = ["Cash", "Credit"];
export const PAYMENT_STATUS_OPTIONS = ["Paid", "Pending", "Partially Paid"];
export const PAYMENT_MODE_OPTIONS = ["Cash", "Card", "UPI", "Insurance", "Credit"];