// lib/admin/pharmacy/stock-update-data.ts
import type { StockUpdateEntry } from "@/types/pharmacy/stock-update-types";

export const STOCK_UPDATE_ENTRIES: StockUpdateEntry[] = [
  {
    id: "1",
    supplier: "Sun Pharma Supply Co.",
    invoiceNumber: "INV-2024-1042",
    purchaseDate: "18 Jun 2024",
    medicineName: "Paracetamol 650",
    batchNo: "P003",
    purchasePrice: 38,
    sellingPrice: 44,
    mrp: 57,
    expiryDate: "Jun 2029",
    quantity: 150,
    gstPercent: 12,
    discountPercent: 5,
    totalAmount: 6035.4,
    status: "Paid",
  },
  {
    id: "2",
    supplier: "MedPlus Distributors",
    invoiceNumber: "INV-2024-1038",
    purchaseDate: "05 Mar 2024",
    medicineName: "Paracetamol 650",
    batchNo: "P002",
    purchasePrice: 40,
    sellingPrice: 45,
    mrp: 56,
    expiryDate: "Dec 2028",
    quantity: 200,
    gstPercent: 12,
    discountPercent: 0,
    totalAmount: 8960,
    status: "Paid",
  },
  {
    id: "3",
    supplier: "Apollo Pharma Traders",
    invoiceNumber: "INV-2024-1051",
    purchaseDate: "20 Apr 2024",
    medicineName: "Azithromycin 500",
    batchNo: "A102",
    purchasePrice: 58,
    sellingPrice: 68,
    mrp: 80,
    expiryDate: "Sep 2026",
    quantity: 100,
    gstPercent: 18,
    discountPercent: 0,
    totalAmount: 6844,
    status: "Unpaid",
  },
  {
    id: "4",
    supplier: "Cipla Wholesale",
    invoiceNumber: "INV-2024-1059",
    purchaseDate: "15 Jan 2024",
    medicineName: "Metformin 500",
    batchNo: "D301",
    purchasePrice: 15,
    sellingPrice: 19,
    mrp: 24,
    expiryDate: "Feb 2028",
    quantity: 300,
    gstPercent: 12,
    discountPercent: 3,
    totalAmount: 4888.8,
    status: "Unpaid",
  },
];

export const SUPPLIER_OPTIONS = ["Sun Pharma Supply Co.", "MedPlus Distributors", "Apollo Pharma Traders", "Cipla Wholesale"];
export const MEDICINE_OPTIONS = ["Paracetamol 650", "Azithromycin 500", "Atorvastatin 20", "Metformin 500"];

export const DEFAULT_STOCK_FORM = {
  supplier: "",
  invoiceNumber: "",
  purchaseDate: "",
  medicineName: "",
  batchNo: "",
  purchasePrice: "",
  sellingPrice: "",
  mrp: "",
  expiryDate: "",
  quantity: "",
  gstPercent: "",
  discountPercent: "",
  status: "Unpaid" as const,
};